(load "~/.config/emacs/Modules/gui.el")
(load "~/.config/emacs/Modules/pConfig.el")

;; Theme
(custom-set-faces
 '(default ((t (:family "Hack Nerd Font" :foundry "SRC" :slant normal :weight regular :height 120 :width normal))))
 '(ansi-color-bold ((t (:inherit bold :foreground "#f5466d"))))
 '(completions-highlight ((t (:background "#bd93f9" :distant-foreground "transparent" :foreground "white"))))
 '(font-latex-bold-face ((t (:inherit bold :foreground "#bd93f9"))))
 '(font-latex-italic-face ((t (:inherit italic :foreground "#bd93f9"))))
 '(font-latex-math-face ((t (:foreground "#37D5ED"))))
 '(font-lock-builtin-face ((t (:foreground "#bd93f9"))))
 '(font-lock-comment-face ((t (:foreground "#f0a5c0"))))
 '(font-lock-constant-face ((t (:foreground "#f0a5c0"))))
 '(font-lock-function-name-face ((t (:foreground "#e3c7fc"))))
 '(font-lock-keyword-face ((t (:foreground "#8897f4"))))
 '(font-lock-string-face ((t (:foreground "#8897f4"))))
 '(font-lock-type-face ((t (:inherit deafult :foreground "#f5466d"))))
 '(font-lock-variable-name-face ((t (:foreground "#e3c7fc"))))
 '(highlight ((t (:background "#bd93f9" :distant-foreground "#bd93f9" :foreground "white"))))
 '(line-number-current-line ((t (:foreground "#f5466d"))))
 '(link ((t (:foreground "#a020f0" :underline t))))
 '(minibuffer-prompt ((t (:foreground "#a020f0"))))
 '(mode-line ((t (:background "#000000" :foreground "#e3c7fc" :box (:line-width (1 . -1) :style released-button)))))
 '(nix-builtin-face ((t (:inherit font-lock-builtin-face :foreground "#f0a5c0"))))
 '(nix-constant-face ((t (:inherit font-lock-constant-face :foreground "#bd93f9"))))
 '(nix-keyword-face ((t (:inherit font-lock-keyword-face :foreground "#f5466d"))))
 '(nobreak-hyphen ((t (:foreground "purple"))))
 '(tab-bar ((t (:inherit variable-pitch :extend t :background "#191724" :distant-foreground "#7e6f90" :foreground "#e3c7fc" :box (:line-width (2 . 2) :color "#322E48" :style released-button) :underline nil :height 0.96))))
 '(tab-bar-tab-inactive ((t (:inherit tab-bar-tab :background "#0F0F17" :foreground "black")))))
(set-face-background 'default "#191724")
(set-face-foreground 'default "#e3c7fb")
(set-face-background 'mode-line "#191724")
(custom-set-variables
 '(fancy-splash-image nil)
 '(tab-bar-close-button-show nil))
